options:
  verbose: true
syncs:
  #IMPORTANT: ensure this name is unique and does not match your other application container name
  [your-site]-unison-sync: # tip: add -sync and you keep consistent names als a convention
    src: './'
    dest: '/var/www'
    sync_strategy: 'unison'
    sync_excludes: ['ignored_folder', '.ignored_dot_folder']
    sync_excludes_type: 'Name'
