dns:
  image: andyshinn/dnsmasq
  restart: always
  ports:
    - "53:53/tcp"
    - "53:53/udp"
  cap_add:
    - NET_ADMIN
  command: --address=/docker/127.0.0.1 --address=/localhost/127.0.0.1 --address=/loc/127.0.0.1
